algoritmo "SomasNumerosInteiros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Anderson Silva Vanin
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Salvador Lemos
// Data atual  : 17/08/2021
var
x,n,soma:inteiro
inicio

para n<- ate 10 faca
 escreval("Entre com o valor")
 leia(x)
 soma<-soma+x
fimpara
escreval("Resultado", soma)
fimalgoritmo